/**
 * 単一装置の import.json を Supabase dev に seed する。
 *
 * 使い方:
 *   npm run seed:device -- A0001
 *   npm run seed:device -- --write-sql A0001
 *
 * 前提:
 *   1. SQL Editor で supabase/scripts/seed_equipment_bundle_fn.sql を Run（初回のみ）
 *   2. .env.local に SUPABASE_SERVICE_ROLE_KEY（service_role 直接取込時）
 */
import { createClient } from "@supabase/supabase-js";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { parseImportBundleJson } from "@/lib/flowchart/importBundleSchema";
import { prepareImportBundleForRpc } from "@/lib/flowchart/prepareImportBundle";
import type { RpcImportBundle } from "@/lib/flowchart/importBundleSchema";

const ROOT = resolve(import.meta.dirname, "..");
const DEVICES_DIR = join(ROOT, "tools/excel_normalize/fixtures/devices");
const FN_SQL = join(ROOT, "supabase/scripts/seed_equipment_bundle_fn.sql");
const GENERATED_SQL = join(ROOT, "supabase/scripts/seed_device_run.sql");

function loadEnvLocal(): void {
  const path = join(ROOT, ".env.local");
  if (!existsSync(path)) return;
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    if (!(key in process.env)) {
      process.env[key] = value;
    }
  }
}

function resolveImportPath(internalCode: string): string {
  const code = internalCode.trim();
  if (!code) {
    throw new Error("社内番号を指定してください（例: A0001）");
  }

  const match = readdirSync(DEVICES_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.startsWith(`${code}_`))
    .map((entry) => join(DEVICES_DIR, entry.name, "import.json"))
    .filter((path) => existsSync(path));

  if (match.length === 0) {
    throw new Error(
      `${code}_* の import.json が見つかりません。npm run excel:a0001:build 等を先に実行してください。`
    );
  }
  if (match.length > 1) {
    throw new Error(
      `${code}_* が複数あります: ${match.map((p) => p.split(/[/\\]/).slice(-2, -1)[0]).join(", ")}`
    );
  }
  return match[0]!;
}

function loadPreparedBundle(importPath: string): RpcImportBundle {
  const jsonText = readFileSync(importPath, "utf8");
  const parsed = parseImportBundleJson(jsonText);
  if (!parsed.ok) {
    throw new Error(`${importPath}: ${parsed.error}`);
  }
  const prepared = prepareImportBundleForRpc(parsed.bundle);
  if (!prepared.ok) {
    throw new Error(`${importPath}:\n${prepared.errors.join("\n")}`);
  }
  return prepared.bundle;
}

function sqlLiteral(bundle: RpcImportBundle): string {
  const json = JSON.stringify(bundle);
  const tag = `$seed_json_${bundle.internal_code.replace(/[^a-zA-Z0-9]/g, "_")}$`;
  return `${tag}${json}${tag}::jsonb`;
}

function writeRunSql(bundle: RpcImportBundle): void {
  const fnSql = readFileSync(FN_SQL, "utf8");
  const body = `-- Generated by scripts/import-device.ts — ${bundle.internal_code}
-- Run entire file in Supabase SQL Editor (includes seed function).

${fnSql}

-- ---------------------------------------------------------------------------
-- Seed ${bundle.internal_code}
-- ---------------------------------------------------------------------------

select public.seed_equipment_bundle(${sqlLiteral(bundle)});
`;

  writeFileSync(GENERATED_SQL, body, "utf8");
  console.log(`Wrote ${GENERATED_SQL}`);
}

async function importViaServiceRole(bundle: RpcImportBundle): Promise<boolean> {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();
  if (!url || !serviceKey) {
    return false;
  }

  const supabase = createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data, error } = await supabase.rpc("seed_equipment_bundle", {
    p_bundle: bundle,
  });
  if (error) {
    if (error.message.includes("Could not find the function")) {
      console.error(
        "seed_equipment_bundle が未作成です。先に seed_equipment_bundle_fn.sql を SQL Editor で Run してください。"
      );
      return false;
    }
    throw new Error(`${bundle.internal_code}: ${error.message}`);
  }

  const row = data as {
    internal_code?: string;
    flows_upserted?: number;
    modules_upserted?: number;
  };
  console.log(
    `OK ${row.internal_code ?? bundle.internal_code}: flows=${row.flows_upserted ?? "?"} modules=${row.modules_upserted ?? "?"}`
  );
  return true;
}

function parseArgs(): { internalCode: string; writeSqlOnly: boolean } {
  const args = process.argv.slice(2).filter((a) => a !== "--");
  const writeSqlOnly = args.includes("--write-sql");
  const positional = args.filter((a) => a !== "--write-sql");
  const internalCode = positional[0] ?? "";
  return { internalCode, writeSqlOnly };
}

async function main(): Promise<void> {
  loadEnvLocal();
  const { internalCode, writeSqlOnly } = parseArgs();
  const importPath = resolveImportPath(internalCode);
  const bundle = loadPreparedBundle(importPath);

  console.log(`Prepared ${bundle.internal_code} (${bundle.display_name})`);
  console.log(`  source: ${importPath}`);

  if (writeSqlOnly) {
    writeRunSql(bundle);
    return;
  }

  const imported = await importViaServiceRole(bundle);
  if (imported) {
    console.log(`Device ${bundle.internal_code} seeded via service_role.`);
    return;
  }

  writeRunSql(bundle);
  console.log("");
  console.log("SUPABASE_SERVICE_ROLE_KEY が未設定のため SQL を生成しました。");
  console.log("Supabase Dashboard → SQL Editor で次を Run してください:");
  console.log(`  ${GENERATED_SQL}`);
  console.log("");
  console.log(
    "または .env.local に SUPABASE_SERVICE_ROLE_KEY を追加して npm run seed:device -- A0001 を再実行。"
  );
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
