/**
 * DEMO-003〜012 の import.json を Supabase に一括 seed する。
 *
 * 使い方:
 *   1. Supabase SQL Editor で supabase/scripts/seed_equipment_bundle_fn.sql を Run（初回のみ）
 *   2. .env.local に SUPABASE_SERVICE_ROLE_KEY を追加（Dashboard → Settings → API）
 *   3. npm run seed:demo-devices
 *
 * service_role が無い場合は --write-sql で SQL を生成し SQL Editor で Run。
 */
import { createClient } from "@supabase/supabase-js";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { parseImportBundleJson } from "@/lib/flowchart/importBundleSchema";
import { prepareImportBundleForRpc } from "@/lib/flowchart/prepareImportBundle";
import type { RpcImportBundle } from "@/lib/flowchart/importBundleSchema";

const ROOT = resolve(import.meta.dirname, "..");
const DEVICES_DIR = join(ROOT, "tools/excel_normalize/fixtures/devices");
const FN_SQL = join(ROOT, "supabase/scripts/seed_equipment_bundle_fn.sql");
const GENERATED_SQL = join(ROOT, "supabase/scripts/seed_demo_devices_run.sql");

function loadEnvLocal(): void {
  const path = join(ROOT, ".env.local");
  if (!existsSync(path)) return;
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    if (!(key in process.env)) {
      process.env[key] = value;
    }
  }
}

function listDemoImportPaths(): string[] {
  return readdirSync(DEVICES_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.startsWith("DEMO-"))
    .map((entry) => join(DEVICES_DIR, entry.name, "import.json"))
    .filter((path) => existsSync(path))
    .sort();
}

function loadPreparedBundles(): RpcImportBundle[] {
  const bundles: RpcImportBundle[] = [];
  for (const importPath of listDemoImportPaths()) {
    const jsonText = readFileSync(importPath, "utf8");
    const parsed = parseImportBundleJson(jsonText);
    if (!parsed.ok) {
      throw new Error(`${importPath}: ${parsed.error}`);
    }
    const prepared = prepareImportBundleForRpc(parsed.bundle);
    if (!prepared.ok) {
      throw new Error(`${importPath}:\n${prepared.errors.join("\n")}`);
    }
    bundles.push(prepared.bundle);
  }
  return bundles;
}

function sqlLiteral(bundle: RpcImportBundle): string {
  const json = JSON.stringify(bundle);
  const tag = `$seed_json_${bundle.internal_code.replace(/[^a-zA-Z0-9]/g, "_")}$`;
  return `${tag}${json}${tag}::jsonb`;
}

function writeRunSql(bundles: RpcImportBundle[]): void {
  const fnSql = readFileSync(FN_SQL, "utf8");
  const calls = bundles
    .map(
      (bundle) => `select public.seed_equipment_bundle(${sqlLiteral(bundle)});`
    )
    .join("\n\n");

  const body = `-- Generated by scripts/import-demo-devices.ts — DEMO seed (${bundles.length} devices)
-- Run entire file in Supabase SQL Editor (includes seed function).

${fnSql}

-- ---------------------------------------------------------------------------
-- Seed DEMO-003 .. DEMO-012
-- ---------------------------------------------------------------------------

${calls}
`;

  writeFileSync(GENERATED_SQL, body, "utf8");
  console.log(`Wrote ${GENERATED_SQL} (${bundles.length} devices)`);
}

async function importViaServiceRole(
  bundles: RpcImportBundle[]
): Promise<boolean> {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();
  if (!url || !serviceKey) {
    return false;
  }

  const supabase = createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  for (const bundle of bundles) {
    const { data, error } = await supabase.rpc("seed_equipment_bundle", {
      p_bundle: bundle,
    });
    if (error) {
      if (error.message.includes("Could not find the function")) {
        console.error(
          "seed_equipment_bundle が未作成です。先に seed_equipment_bundle_fn.sql を SQL Editor で Run してください。"
        );
        return false;
      }
      throw new Error(`${bundle.internal_code}: ${error.message}`);
    }
    const row = data as {
      internal_code?: string;
      flows_upserted?: number;
      modules_upserted?: number;
    };
    console.log(
      `OK ${row.internal_code ?? bundle.internal_code}: flows=${row.flows_upserted ?? "?"} modules=${row.modules_upserted ?? "?"}`
    );
  }
  return true;
}

async function main(): Promise<void> {
  loadEnvLocal();
  const writeSqlOnly = process.argv.includes("--write-sql");
  const bundles = loadPreparedBundles();

  if (bundles.length === 0) {
    console.error(
      "DEMO-* import.json が見つかりません。npm run excel:demo-devices を先に実行してください。"
    );
    process.exit(1);
  }

  console.log(`Prepared ${bundles.length} device bundle(s)`);

  if (writeSqlOnly) {
    writeRunSql(bundles);
    return;
  }

  const imported = await importViaServiceRole(bundles);
  if (imported) {
    console.log("All demo devices seeded via service_role.");
    return;
  }

  writeRunSql(bundles);
  console.log("");
  console.log("SUPABASE_SERVICE_ROLE_KEY が未設定のため SQL を生成しました。");
  console.log("Supabase Dashboard → SQL Editor で次を Run してください:");
  console.log(`  ${GENERATED_SQL}`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
